# Generated by Django 2.2 on 2020-03-04 07:31

from django.db import migrations
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Quntity',
            field=my_app.models.ListField(blank=True),
        ),
    ]
