# Generated by Django 2.2.2 on 2020-03-17 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_desc', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('request_updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestmade', to=settings.AUTH_USER_MODEL)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='api_user.Service')),
            ],
        ),
    ]
