# Generated by Django 2.2.2 on 2020-03-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestservice',
            old_name='service_id',
            new_name='service_name',
        ),
    ]
