# Generated by Django 2.2.2 on 2020-03-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0005_auto_20200317_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestservice',
            old_name='service_name',
            new_name='service_id',
        ),
    ]
