# Generated by Django 2.2.2 on 2020-03-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0007_auto_20200317_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_id',
            new_name='service_name',
        ),
    ]
