# Generated by Django 2.2.2 on 2020-03-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0008_auto_20200317_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestservice',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='requestservice',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_provider',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='RequestService',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
