# Generated by Django 2.2.2 on 2020-03-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0010_comment_requestservice_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestservice',
            old_name='service_id',
            new_name='service_name',
        ),
    ]
