# Generated by Django 2.2.2 on 2020-03-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0013_auto_20200318_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestservice',
            old_name='service_name',
            new_name='service_id',
        ),
    ]
