# Generated by Django 2.2.2 on 2020-03-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0015_auto_20200319_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='consumer',
            new_name='author',
        ),
    ]
